## this function was generated by chatGPT

cdf_to_quantiles <- function(cdf_df, quantile_probs, x_col = "x", cdf_col = "cdf") {
  # Check for required columns
  if (!all(c(x_col, cdf_col) %in% names(cdf_df))) {
    stop("Provided column names not found in the data frame.")
  }

  # Ensure data is sorted by cdf values
  cdf_df <- cdf_df[order(cdf_df[[cdf_col]]), ]

  # Remove duplicates in CDF (to ensure monotonicity)
  cdf_df <- cdf_df[!duplicated(cdf_df[[cdf_col]]), ]

  # Use linear interpolation to find the quantiles
  approx(
    x = cdf_df[[cdf_col]],
    y = cdf_df[[x_col]],
    xout = quantile_probs,
    rule = 2  # allow extrapolation if needed
  )$y
}

## example by Nick Reich

# Simulated example CDF
example_length <- 10
x_start <- 0 ## to see extrapolation in action, set to 5
cdf_example <- data.frame(
  x = seq(x_start, 10, length.out = example_length),
  cdf = pnorm(seq(x_start, 10, length.out = example_length), mean = 5, sd = .5)
)

# Get quantiles at 10%, 50%, and 90%
transformed_example <- tibble(
  quantiles = c(0.1, 0.5, 0.9),
  values = cdf_to_quantiles(cdf_example, quantiles)
)

plot(cdf_example$x, cdf_example$cdf, xlim = c(0, 10), ylim = c(0, 1))
points(transformed_example$values, transformed_example$quantiles, col = "red")
